### ISSUE TITLE
Add tags for Composable Automation compatibility

### ISSUE THREAD

**Issue by swordglowsblue** [swordglowsblue/redstone-tweaks#1]
[CompAuto](https://minecraft.curseforge.com/projects/composable-automation)'s photodetector uses a handful of tags to determine the color of blocks, which I'd like to add compatibility for. The following tags should be added with regards to dyed wire / redstone blocks, and potentially some other blocks:

- `red`, `strong_red`
- `green`, `strong_green`
- `blue`, `strong_blue`

The tag files [in CompAuto's repo](https://gitlab.com/sargunv-mc-mods/composable-automation/tree/1.14/src/main/resources/data/composableautomation/tags/blocks) can be used as examples of which blocks should go in which tags. It would also be good to add compatibility for CompAuto's dispenser toggling to the analog redstone block and torch levers, via the `toggleable` tag.

**Comment by swordglowsblue** [comment]
Mentioning @sargunv since this directly relates to his mod =)

**Comment by sargunv** [comment]
I'd be happy to PR this if you like

**Comment by swordglowsblue** [comment]
If you think you can find your way around my resource gen system (or just drop them in `predef` but genning them would be preferable), I'd much appreciate the help. I'm happy to do it myself if you don't want to dig through my mess of a gen script, though.

**Comment by swordglowsblue** [comment]
Added by dbf595e. May add `toggleable` later, but the cross-powering of the dispenser causes issues I can't be bothered to deal with right now.
