### ISSUE TITLE
Feature Request - toggleable not gate.

### ISSUE THREAD

**Issue by prozacgod** [swordglowsblue/redstone-tweaks#3]
It would be nice if the not gates could be toggled by clicking on them, that way I can slap a bunch of them down in a repeated pattern and then if I need an inverted signal I can simply whack it.

I know it's the same as a repeater, but it's ... kinda not?

I was entertaining the idea of making some digital components, probably not a cpu, but... parts of one.

It would be super usefull for this feature, when making things like "address decoders", or "rom" especiallying if they could be clicked then you can run around programming the rom.

**Comment by swordglowsblue** [comment]
Wrong mod, sorry. Also... just use a redstone torch?
